# Generated by Django 4.1.7 on 2023-05-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb3dApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='savedCrags',
            field=models.ManyToManyField(blank=True, related_name='saved_crags', to='climb3dApp.crag'),
        ),
    ]
